"""
Stage 1b — Generate Employee Roster
Outputs: data/qsr_employees.csv
Records: 15 employees
"""

import pandas as pd
import os

employees = [
    {
        "emp_id":             "E001",
        "name":               "Maria Santos",
        "role":               "Manager",
        "min_hours":          35,
        "max_hours":          44,
        "max_days_per_week":  5,
        "days_off":           "Sunday",
        "availability_start": 6,
        "availability_end":   23,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        24.50,
    },
    {
        "emp_id":             "E002",
        "name":               "James Reyes",
        "role":               "Manager",
        "min_hours":          35,
        "max_hours":          44,
        "max_days_per_week":  5,
        "days_off":           "Saturday",
        "availability_start": 6,
        "availability_end":   23,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        24.50,
    },
    {
        "emp_id":             "E003",
        "name":               "Ana Dela Cruz",
        "role":               "Shift Supervisor",
        "min_hours":          30,
        "max_hours":          40,
        "max_days_per_week":  5,
        "days_off":           "Friday",
        "availability_start": 6,
        "availability_end":   21,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        20.00,
    },
    {
        "emp_id":             "E004",
        "name":               "Kevin Park",
        "role":               "Shift Supervisor",
        "min_hours":          30,
        "max_hours":          40,
        "max_days_per_week":  5,
        "days_off":           "Monday",
        "availability_start": 10,
        "availability_end":   23,
        "preferred_shift":    "afternoon",
        "min_rest_hours":     10,
        "hourly_rate":        20.00,
    },
    {
        "emp_id":             "E005",
        "name":               "Priya Nair",
        "role":               "Shift Supervisor",
        "min_hours":          30,
        "max_hours":          40,
        "max_days_per_week":  5,
        "days_off":           "Wednesday",
        "availability_start": 8,
        "availability_end":   22,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        20.00,
    },
    {
        "emp_id":             "E006",
        "name":               "Carlos Mendez",
        "role":               "Crew - Full Time",
        "min_hours":          28,
        "max_hours":          40,
        "max_days_per_week":  5,
        "days_off":           "Tuesday",
        "availability_start": 6,
        "availability_end":   22,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        17.50,
    },
    {
        "emp_id":             "E007",
        "name":               "Sophie Tremblay",
        "role":               "Crew - Full Time",
        "min_hours":          28,
        "max_hours":          40,
        "max_days_per_week":  5,
        "days_off":           "Thursday",
        "availability_start": 7,
        "availability_end":   23,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        17.50,
    },
    {
        "emp_id":             "E008",
        "name":               "Diego Rivera",
        "role":               "Crew - Full Time",
        "min_hours":          28,
        "max_hours":          40,
        "max_days_per_week":  5,
        "days_off":           "Sunday",
        "availability_start": 6,
        "availability_end":   21,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        17.50,
    },
    {
        "emp_id":             "E009",
        "name":               "Fatima Al-Hassan",
        "role":               "Crew - Full Time",
        "min_hours":          28,
        "max_hours":          40,
        "max_days_per_week":  5,
        "days_off":           "Saturday",
        "availability_start": 9,
        "availability_end":   23,
        "preferred_shift":    "afternoon",
        "min_rest_hours":     10,
        "hourly_rate":        17.50,
    },
    {
        "emp_id":             "E010",
        "name":               "Liam Johnson",
        "role":               "Crew - Part Time",
        "min_hours":          12,
        "max_hours":          24,
        "max_days_per_week":  4,
        "days_off":           "Monday,Wednesday",
        "availability_start": 14,
        "availability_end":   23,
        "preferred_shift":    "evening",
        "min_rest_hours":     10,
        "hourly_rate":        16.00,
    },
    {
        "emp_id":             "E011",
        "name":               "Aisha Mohammed",
        "role":               "Crew - Part Time",
        "min_hours":          12,
        "max_hours":          24,
        "max_days_per_week":  4,
        "days_off":           "Tuesday,Thursday",
        "availability_start": 6,
        "availability_end":   15,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        16.00,
    },
    {
        "emp_id":             "E012",
        "name":               "Emma Leblanc",
        "role":               "Crew - Part Time",
        "min_hours":          12,
        "max_hours":          24,
        "max_days_per_week":  4,
        "days_off":           "Monday,Friday",
        "availability_start": 10,
        "availability_end":   19,
        "preferred_shift":    "afternoon",
        "min_rest_hours":     10,
        "hourly_rate":        16.00,
    },
    {
        "emp_id":             "E013",
        "name":               "Noah Kim",
        "role":               "Crew - Part Time",
        "min_hours":          12,
        "max_hours":          24,
        "max_days_per_week":  4,
        "days_off":           "Wednesday,Sunday",
        "availability_start": 15,
        "availability_end":   23,
        "preferred_shift":    "evening",
        "min_rest_hours":     10,
        "hourly_rate":        16.00,
    },
    {
        "emp_id":             "E014",
        "name":               "Isabelle Okonkwo",
        "role":               "Crew - Part Time",
        "min_hours":          12,
        "max_hours":          24,
        "max_days_per_week":  4,
        "days_off":           "Saturday",
        "availability_start": 6,
        "availability_end":   18,
        "preferred_shift":    "morning",
        "min_rest_hours":     10,
        "hourly_rate":        16.00,
    },
    {
        "emp_id":             "E015",
        "name":               "Marco Ferreira",
        "role":               "Crew - Part Time",
        "min_hours":          12,
        "max_hours":          24,
        "max_days_per_week":  4,
        "days_off":           "Sunday,Monday",
        "availability_start": 11,
        "availability_end":   23,
        "preferred_shift":    "afternoon",
        "min_rest_hours":     10,
        "hourly_rate":        16.00,
    },
]

df = pd.DataFrame(employees)

output_path = os.path.join(os.path.dirname(__file__), "..", "data", "qsr_employees.csv")
output_path = os.path.normpath(output_path)
df.to_csv(output_path, index=False)

print(f"DONE: qsr_employees.csv saved -- {len(df)} employees")
print()
print(df[["emp_id", "name", "role", "days_off"]].to_string(index=False))
